(function () {
  function initSounds() {
    // Battle cues are generated by index.html and the committed music files
    // are loaded there. The old assets/sounds/*.mp3 catalogue never existed,
    // so do not issue guaranteed 404 requests for it.
    if (window.audioManager && typeof window.audioManager.loadSettings === 'function') {
      window.audioManager.loadSettings();
    }
    setupSoundTriggers();
  }

  function setupSoundTriggers() {
    if (typeof window.playSound !== 'function') return;
    const originalPlaySound = window.playSound;
    window.playSound = function (kind) {
      return originalPlaySound(kind);
    };
  }

  window.initSounds = initSounds;
  window.setupSoundTriggers = setupSoundTriggers;
})();
